version: "3.1"

language: fr

pipeline:
  # Prétraitement amélioré pour le français
  - name: SpacyNLP
    model: "fr_core_news_lg"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  
  # Feature engineering optimisé
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
    token_pattern: r'\w+|\$[\d\.]+|\S+'
  
  # Classificateur principal renforcé
  - name: DIETClassifier
    epochs: 100
    hidden_layers_sizes:
      text: [256, 128]
    embedding_dimension: 256
    drop_rate: 0.2
    weight_sparsity: 0.7
    constrain_similarities: true
  
  # Pour gérer les réponses complexes
  - name: ResponseSelector
    epochs: 150
    retrieval_intent: "faq"

  - name: FallbackPolicy
    nlu_threshold: 0.7
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
    core_fallback_threshold: 0.1
    enable_fallback_prediction: false  # Désactivé temporairement
  - name: TEDPolicy
    max_history: 5
    epochs: 300
    batch_size: [64, 128]
    learning_rate: 0.0005