"""Nouvelle migration initiale

Revision ID: 04d56213a91b
Revises: 
Create Date: 2025-05-19 23:58:16.865491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d56213a91b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hebergements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('type_hebergement', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('prix_nuit', sa.Float(), nullable=True),
    sa.Column('capacite', sa.Integer(), nullable=True),
    sa.Column('equipements', sa.Text(), nullable=True),
    sa.Column('note_moyenne', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hebergements_id'), 'hebergements', ['id'], unique=False)
    op.create_table('flight_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('itinerary_id', sa.String(length=50), nullable=False),
    sa.Column('passengers', sa.JSON(), nullable=True),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_table('flight_bookings')
    op.drop_index(op.f('ix_hebergements_id'), table_name='hebergements')
    op.drop_table('hebergements')
    # ### end Alembic commands ###
